/**
 * wordlists.mjs — AI-slop tell vocabulary.
 *
 * Sources:
 *  - PraveenTechWorld internal avoid-list (curated from SEO/reviewer feedback)
 *  - Liang et al., Nature Human Behaviour 2025 ("realm", "intricate", "showcasing", "pivotal" surged after ChatGPT)
 *  - Kobak et al., Science Advances 2025 (excess-vocabulary in 15M biomedical abstracts; "delve" +~1500% 2022-2024)
 *  - antydizajn/ai-slop-detect, hwajongpark/slop-gate, fbuchinger/smellcheck pattern packs
 *  - Guo et al. 2023 (em-dash present in ~73% of GPT-4 long-form samples vs ~12% human)
 *
 * Scoring semantics (see analyzer.mjs):
 *  - BUZZWORDS_TIER1  -> weight 1 per occurrence (per 300 words)
 *  - BUZZWORDS_TIER2  -> weight 0.5, counted only when the SAME word repeats or density is high
 *                        (these are legitimate words in moderation; overuse is the tell)
 *  - TELL_PHRASES     -> weight 2 per occurrence (multi-word clichés, strongest signal)
 *  - WEAK_OPENERS     -> weight 2, only counted at sentence starts
 */

export const BUZZWORDS_TIER1 = [
  { word: "delve", hint: 'Say "dig into", "explore", or just state it.' },
  { word: "delving", hint: 'Say "digging into" or "exploring".' },
  { word: "delved", hint: 'Say "dug into" or "explored".' },
  { word: "tapestry", hint: 'Say "range", "mix", "set". A tapestry of X is a signature AI phrase.' },
  { word: "unlock", hint: 'Only if literal (a lock). Otherwise say "get", "enable", "open up".' },
  { word: "unlocking", hint: 'Say "enabling", "getting", "starting".' },
  { word: "unleash", hint: 'Say "use", "apply", "let loose".' },
  { word: "elevate", hint: 'Say "improve", "raise", "boost".' },
  { word: "elevating", hint: 'Say "improving".' },
  { word: "empower", hint: 'Say "help", "enable", "let".' },
  { word: "empowering", hint: 'Say "helpful", "enabling".' },
  { word: "seamless", hint: "Say what actually works smoothly, or just \"smooth\"." },
  { word: "seamlessly", hint: 'Say "smoothly" or drop it.' },
  { word: "robust", hint: "Fine in statistics. Elsewhere say \"solid\", \"reliable\", \"dependable\"." },
  { word: "leverage", hint: 'Say "use", "build on", "take advantage of".' },
  { word: "leveraging", hint: 'Say "using".' },
  { word: "pivotal", hint: 'Say "key", "central", "decisive".' },
  { word: "paramount", hint: 'Say "most important", "essential".' },
  { word: "integral", hint: 'Say "essential", "built-in".' },
  { word: "intricate", hint: 'Say "complex", "detailed".' },
  { word: "multifaceted", hint: 'Say "many-sided", "complex", or drop it.' },
  { word: "holistic", hint: 'Say "overall", "whole-picture", or drop it.' },
  { word: "nuanced", hint: 'Say "subtle", "careful", "detailed".' },
  { word: "underscore", hint: 'Say "show", "emphasize", "underline".' },
  { word: "underscores", hint: 'Say "shows".' },
  { word: "resonate", hint: 'Say "connect with", "ring true".' },
  { word: "resonates", hint: 'Say "connects".' },
  { word: "groundbreaking", hint: 'Say "new", "first", or name the actual innovation.' },
  { word: "invaluable", hint: 'Say "useful", "worth its weight", or show why.' },
  { word: "relentless", hint: 'Say "tireless", "steady", or drop it.' },
  { word: "enlightening", hint: 'Say "revealing", "helpful".' },
  { word: "esteemed", hint: 'Say "respected", "well-known".' },
  { word: "cognizant", hint: 'Say "aware".' },
  { word: "conceptualize", hint: 'Say "imagine", "think of", "design".' },
  { word: "discern", hint: 'Say "see", "spot", "tell apart".' },
  { word: "elucidate", hint: 'Say "explain", "clarify".' },
  { word: "unravel", hint: 'Say "work out", "figure out", "untangle".' },
  { word: "cultivate", hint: 'Say "build", "grow", "develop".' },
  { word: "profound", hint: 'Say "deep", "major", "big".' },
  { word: "synergy", hint: 'Say "combined effect", "fit".' },
  { word: "synergize", hint: 'Say "work together".' },
  { word: "foster", hint: 'Say "encourage", "build", "support".' },
  { word: "fostering", hint: 'Say "building", "supporting".' },
  { word: "endeavor", hint: 'Say "effort", "project", "attempt".' },
  { word: "endeavour", hint: 'Say "effort", "project".' },
  { word: "embark", hint: 'Say "start", "begin".' },
  { word: "embarked", hint: 'Say "started", "began".' },
  { word: "peril", hint: 'Say "danger", "risk".' },
  { word: "pertains", hint: 'Say "relates to", "applies to".' },
  { word: "pertinent", hint: 'Say "relevant".' },
  { word: "amplify", hint: 'Say "boost", "increase", "strengthen".' },
  { word: "adhere", hint: 'Say "follow", "stick to".' },
  { word: "adherence", hint: 'Say "following".' },
  { word: "streamline", hint: 'Say "simplify", "speed up".' },
  { word: "streamlined", hint: 'Say "simplified", "faster".' },
  { word: "revolutionize", hint: 'Say "change", "transform" - or show the actual change.' },
  { word: "revolutionizing", hint: 'Say "changing".' },
  { word: "game-changer", hint: "Say what it actually changes." },
  { word: "game-changing", hint: "Say what it actually changes." },
  { word: "cutting-edge", hint: 'Say "latest", "newest", "new".' },
  { word: "state-of-the-art", hint: 'Say "current", "modern".' },
  { word: "best-in-class", hint: 'Say "top", or show a comparison.' },
  { word: "world-class", hint: 'Say "top", or show a comparison.' },
  { word: "harness", hint: 'Say "use", "put to work".' },
  { word: "harnessing", hint: 'Say "using".' },
  { word: "landscape", hint: 'Only if geography. Else say "world", "market", "scene".' },
  { word: "realm", hint: 'Say "area", "field", "world".' },
  { word: "showcasing", hint: 'Say "showing".' },
  { word: "showcases", hint: 'Say "shows".' },
  { word: "treasure", hint: 'Say "gold mine", "collection", or name the thing.' },
  { word: "testament", hint: 'Say "proof", "sign", "evidence".' },
  { word: "striking", hint: "Fine about a visual. Elsewhere say \"notable\", \"unusual\"." },
  { word: "lucrative", hint: 'Say "profitable", "well-paid".' },
  { word: "ever-evolving", hint: 'Say "changing", "shifting".' },
  { word: "ever-changing", hint: 'Say "changing".' },
  { word: "facilitate", hint: 'Say "help", "make easier", "support".' },
  { word: "facilitating", hint: 'Say "helping".' },
  { word: "encompass", hint: 'Say "cover", "include".' },
  { word: "encompasses", hint: 'Say "covers", "includes".' },
  { word: "characterized", hint: 'Say "marked by", "known for".' },
  { word: "underpin", hint: 'Say "support", "back".' },
  { word: "underpins", hint: 'Say "supports", "backs".' },
  { word: "underpinning", hint: 'Say "supporting", "base".' },
  { word: "embody", hint: 'Say "represent", "stand for".' },
  { word: "epitomize", hint: 'Say "represent".' },
  { word: "witness", hint: 'Say "see", "watch". "Witness the" is an AI habit.' },
  { word: "comprehensive", hint: 'Say "thorough", "full", or drop it.' },
  { word: "insight", hint: 'Say "finding", "lesson", "observation" - or name it.' },
  { word: "insights", hint: 'Say "findings", "lessons", "observations".' },
  { word: "expertise", hint: 'Say "skill", "know-how", "experience".' },
  { word: "offerings", hint: 'Say "products", "services", "tools".' },
  { word: "valuable", hint: 'Say "useful", or show the value.' },
  { word: "crucial", hint: 'Say "key", "important", "vital" - or show why.' },
  { word: "significant", hint: 'Say "big", "notable", "real".' },
  { word: "profoundly", hint: 'Say "deeply", "hugely".' },
  { word: "effectively", hint: "Usually droppable. Say \"in practice\" if you mean that." },
  { word: "essentially", hint: "Usually droppable. Say \"basically\" or \"in short\"." },
  { word: "myriad", hint: 'Say "many", "a host of".' },
  { word: "plethora", hint: 'Say "many", "a lot of".' },
];

export const BUZZWORDS_TIER2 = [
  { word: "crucial", hint: "" },
  { word: "valuable", hint: "" },
  { word: "insights", hint: "" },
  { word: "significant", hint: "" },
  { word: "complexity", hint: "" },
  { word: "recognize", hint: "" },
  { word: "adapt", hint: "" },
  { word: "promote", hint: "" },
  { word: "critique", hint: "" },
  { word: "comprehensive", hint: "" },
  { word: "implications", hint: "" },
  { word: "complementary", hint: "" },
  { word: "perspectives", hint: "" },
  { word: "facilitate", hint: "" },
  { word: "enhance", hint: "" },
  { word: "enhancing", hint: "" },
  { word: "enhanced", hint: "" },
  { word: "emphasize", hint: "" },
  { word: "explore", hint: "" },
  { word: "exploring", hint: "" },
  { word: "explores", hint: "" },
  { word: "adhere", hint: "" },
  { word: "folks", hint: "" },
  { word: "systemic", hint: "" },
  { word: "inherent", hint: "" },
  { word: "endeavour", hint: "" },
  { word: "unlock", hint: "" },
  { word: "unleash", hint: "" },
  { word: "foster", hint: "" },
  { word: "intricate", hint: "" },
  { word: "pivotal", hint: "" },
  { word: "peril", hint: "" },
  { word: "pertinent", hint: "" },
  { word: "amplify", hint: "" },
];

export const TELL_PHRASES = [
  { phrase: "in today's fast-paced world", hint: 'Cut. Start with the actual subject.' },
  { phrase: "in today's fast-paced digital world", hint: 'Cut. Start with the actual subject.' },
  { phrase: "in today's digital landscape", hint: 'Say "now", "these days", or cut it.' },
  { phrase: "in today's digital age", hint: 'Say "now", "these days".' },
  { phrase: "in today's world", hint: 'Say "now".' },
  { phrase: "in the ever-evolving landscape", hint: 'Say "in the changing world".' },
  { phrase: "in the ever-evolving world", hint: 'Say "in the changing world".' },
  { phrase: "in the ever-changing landscape", hint: 'Say "in the changing world".' },
  { phrase: "navigate the complexities", hint: 'Say "handle the complexity" or name the actual steps.' },
  { phrase: "navigate the world of", hint: 'Say "work in", "deal with".' },
  { phrase: "navigate the landscape", hint: 'Say "work in", "deal with".' },
  { phrase: "when it comes to", hint: 'Usually droppable: "When it comes to X" -> "For X" or just start.' },
  { phrase: "it's important to note that", hint: 'Cut. If it were important, it would be the sentence.' },
  { phrase: "it is important to note that", hint: 'Cut.' },
  { phrase: "it's worth noting that", hint: 'Cut.' },
  { phrase: "it is worth noting that", hint: 'Cut.' },
  { phrase: "it's crucial to", hint: 'Say "you need to", "make sure to".' },
  { phrase: "it is crucial to", hint: 'Say "you need to".' },
  { phrase: "it's essential to", hint: 'Say "you should".' },
  { phrase: "it is essential to", hint: 'Say "you should".' },
  { phrase: "let's dive in", hint: 'Cut. Start the content.' },
  { phrase: "let's dive into", hint: 'Cut, or say "here is".' },
  { phrase: "let's delve into", hint: 'Cut, or say "here is".' },
  { phrase: "dive into", hint: 'Say "look at", "go through", "try".' },
  { phrase: "deep dive into", hint: 'Say "close look at".' },
  { phrase: "a deep dive into", hint: 'Say "a close look at".' },
  { phrase: "at the end of the day", hint: 'Cut, or say "ultimately", "in the end".' },
  { phrase: "in conclusion", hint: 'Cut. End on the point, not a signpost.' },
  { phrase: "to sum up", hint: 'Cut.' },
  { phrase: "in summary", hint: 'Cut.' },
  { phrase: "overall, it's clear that", hint: 'Cut. Say the finding.' },
  { phrase: "it's clear that", hint: 'Say the finding without the lead-in.' },
  { phrase: "it is clear that", hint: 'Say the finding without the lead-in.' },
  { phrase: "it's no secret that", hint: 'Say the fact directly.' },
  { phrase: "in essence", hint: 'Cut, or say "in short".' },
  { phrase: "unlock the power of", hint: 'Say "use", "get the most out of".' },
  { phrase: "unlock the potential of", hint: 'Say "make the most of".' },
  { phrase: "unlock the full potential", hint: 'Say "make the most of".' },
  { phrase: "unleash the power of", hint: 'Say "use".' },
  { phrase: "harness the power of", hint: 'Say "use".' },
  { phrase: "harness the power", hint: 'Say "use".' },
  { phrase: "the power of", hint: "Vague inflation. Name the thing that works." },
  { phrase: "a testament to", hint: 'Say "proof of", "sign of".' },
  { phrase: "serves as a testament", hint: 'Say "shows".' },
  { phrase: "a treasure trove of", hint: 'Say "a gold mine of", "lots of".' },
  { phrase: "in the realm of", hint: 'Say "in the field of", "in".' },
  { phrase: "in the world of", hint: 'Say "in".' },
  { phrase: "take your", hint: "Check for \"take your X to the next level\"." },
  { phrase: "to the next level", hint: 'Say "better", "further", or show the improvement.' },
  { phrase: "take it to the next level", hint: 'Say "go further".' },
  { phrase: "transform your workflow", hint: 'Say what actually changes in the workflow.' },
  { phrase: "transform your business", hint: 'Say what actually changes.' },
  { phrase: "revolutionize the way", hint: 'Say "change how".' },
  { phrase: "change the game", hint: 'Say what changes.' },
  { phrase: "game changer", hint: 'Say what it changes.' },
  { phrase: "a game-changer", hint: 'Say what it changes.' },
  { phrase: "cutting-edge technology", hint: 'Say "newest technology".' },
  { phrase: "state-of-the-art", hint: 'Say "current", "modern".' },
  { phrase: "seamless integration", hint: 'Say "easy setup", "it works with".' },
  { phrase: "seamlessly integrate", hint: 'Say "work with".' },
  { phrase: "robust solution", hint: 'Say "solid option", "reliable tool".' },
  { phrase: "feel free to", hint: 'Say "please", or just state the option.' },
  { phrase: "don't hesitate to", hint: 'Say "please".' },
  { phrase: "do not hesitate to", hint: 'Say "please".' },
  { phrase: "please don't hesitate", hint: 'Say "please".' },
  { phrase: "if you have any questions", hint: "Fine in email; cut in articles." },
  { phrase: "let me know if", hint: "Chat-speak; usually cut." },
  { phrase: "i hope this helps", hint: 'Cut, or say what to try next.' },
  { phrase: "as an ai", hint: "An AI can't hide behind being an AI." },
  { phrase: "as a language model", hint: "Cut." },
  { phrase: "play a crucial role", hint: 'Say "matters", "is key".' },
  { phrase: "plays a crucial role", hint: 'Say "matters", "is key".' },
  { phrase: "plays a vital role", hint: 'Say "matters", "is key".' },
  { phrase: "paving the way for", hint: 'Say "enabling", "making way for".' },
  { phrase: "paved the way for", hint: 'Say "enabled".' },
  { phrase: "sets the stage for", hint: 'Say "prepares for".' },
  { phrase: "lays the groundwork", hint: 'Say "builds the base".' },
  { phrase: "laying the groundwork", hint: 'Say "building the base".' },
  { phrase: "shed light on", hint: 'Say "explain", "reveal", "show".' },
  { phrase: "sheds light on", hint: 'Say "explains", "reveals".' },
  { phrase: "shedding light on", hint: 'Say "explaining".' },
  { phrase: "in the age of", hint: 'Say "now that", "with".' },
  { phrase: "in an era of", hint: 'Say "now".' },
  { phrase: "in the era of", hint: 'Say "now".' },
  { phrase: "in the fast-paced world", hint: 'Cut.' },
  { phrase: "look no further", hint: 'Cut, or say "here is".' },
  { phrase: "whether you're a", hint: "Usually replaceable with direct address: \"For beginners or experts\"" },
  { phrase: "whether you are a", hint: "Usually replaceable with direct address." },
  { phrase: "keep in mind that", hint: 'Cut, or say "note".' },
  { phrase: "a wide range of", hint: 'Say "many", "a range of".' },
  { phrase: "an array of", hint: 'Say "many", "a set of".' },
  { phrase: "a myriad of", hint: 'Say "many".' },
  { phrase: "plethora of", hint: 'Say "lots of".' },
  { phrase: "in this comprehensive guide", hint: "Don't describe the guide; start it." },
  { phrase: "this comprehensive guide", hint: "Don't describe the guide; start it." },
  { phrase: "in this article, we will", hint: 'Cut. "This article" self-reference is a tell.' },
  { phrase: "in this article, i will", hint: 'Cut.' },
  { phrase: "this article will", hint: 'Cut.' },
  { phrase: "the intersection of", hint: 'Say "the overlap of", or name it.' },
  { phrase: "at its core", hint: 'Say "basically", "fundamentally" - or cut.' },
  { phrase: "at the core", hint: "Usually cut." },
  { phrase: "get ready to", hint: 'Cut, or say "here is how to".' },
  { phrase: "are you ready to", hint: "Marketing voice; check the audience." },
  { phrase: "whether you're looking for", hint: "Usually cut." },
  { phrase: "look for", hint: "Often droppable." },
  { phrase: "the future of", hint: "Often hype. Say what happens next." },
  { phrase: "the key to", hint: "Often hype. Name the actual key." },
  { phrase: "in today's digital-first world", hint: "Cut." },
  { phrase: "digital-first", hint: "Jargon; say \"online\"." },
  { phrase: "user-centric", hint: 'Say "built around users".' },
  { phrase: "user-friendly", hint: 'Say "easy to use".' },
  { phrase: "top-notch", hint: 'Say "top", "excellent".' },
  { phrase: "unmatched", hint: "Usually hype; show the match." },
  { phrase: "unparalleled", hint: "Usually hype; show the comparison." },
  { phrase: "meticulous", hint: 'Say "careful", "detailed".' },
  { phrase: "journey", hint: '"AI journey" is a tell. Say "path", "process", "work".' },
  { phrase: "onboarding", hint: 'Say "getting started", "setup".' },
  { phrase: "roadmap", hint: "Fine in product docs; elsewhere say \"plan\"." },
  { phrase: "game plan", hint: 'Say "plan".' },
  { phrase: "level up", hint: 'Say "improve", "advance".' },
  { phrase: "step up", hint: 'Say "improve".' },
  { phrase: "crucial aspect", hint: 'Say "key part".' },
  { phrase: "important aspect", hint: 'Say "key part".' },
  { phrase: "key aspect", hint: 'Say "key part".' },
  { phrase: "vital aspect", hint: 'Say "key part".' },
];

export const WEAK_OPENERS = [
  { phrase: "certainly,", hint: "Chat-style opener. Cut." },
  { phrase: "of course,", hint: "Chat-style opener. Cut or use in speech only." },
  { phrase: "absolutely,", hint: "Chat-style opener. Cut." },
  { phrase: "great question,", hint: "Chat-style opener. Cut." },
  { phrase: "that's a great question", hint: "Chat-style opener. Cut." },
  { phrase: "that's a fantastic", hint: "Chat-style opener. Cut." },
  { phrase: "i'd be happy to", hint: "Chat-style. Cut or say what you will do." },
  { phrase: "i would be happy to", hint: "Chat-style. Cut." },
  { phrase: "i'd love to", hint: "Chat-style. Cut." },
  { phrase: "here's what you need to know", hint: "Cut the meta; just say it." },
  { phrase: "here is what you need to know", hint: "Cut the meta." },
  { phrase: "let me walk you through", hint: "Fine once; repeated is a tell." },
  { phrase: "let me guide you through", hint: "Fine once; repeated is a tell." },
  { phrase: "in this blog post", hint: "Self-reference tell. Cut." },
  { phrase: "in this post", hint: "Self-reference tell. Cut." },
];

/**
 * Filler words counted as a soft "actually"-style signal.
 * "actually" is the documented overuse word (Justin Feinberg note).
 */
export const FILLER_WORDS = ["actually", "literally", "frankly"];

/**
 * Typography tells - characters LLMs emit from typeset training data
 * that humans rarely type by hand. (fbuchinger/smellcheck, Guo et al. 2023)
 */
export const TYPOGRAPHY_TELLS = [
  { char: "—", name: "em dash", hint: "Replace with \" - \" or a comma/colon." },
  { char: "–", name: "en dash", hint: "Usually replace with a hyphen." },
  { char: "…", name: "horizontal ellipsis", hint: "Use three dots if you must." },
  { char: "‘", name: "curly apostrophe", hint: "Straight quotes are fine." },
  { char: "’", name: "curly apostrophe", hint: "Straight quotes are fine." },
  { char: "“", name: "curly quote", hint: "Straight quotes are fine." },
  { char: "”", name: "curly quote", hint: "Straight quotes are fine." },
  { char: "\u00a0", name: "non-breaking space", hint: "Plain spaces are fine." },
];
